version: '4.21.x.{build}'

image:
  - Visual Studio 2017

configuration:
  - Debug
  - Release

platform:
  - x64
  - Win32
  - AVX2
  - ARM64
  - ARM

environment:
  matrix:
    - compiler: MSVC
    - compiler: Clang

shallow_clone: true

test: off

deploy: off

matrix:
  fast_finish: true
  exclude:
    - configuration: Debug
    - platform: ARM
      compiler: Clang

# No reversion when shallow clone is enabled.
# before_build:
#  - cmd: CALL update_rev.bat

for:
  - # MSVC x64 Debug
    matrix:
      only:
        - configuration: Debug
          platform: x64
          compiler: MSVC

    build_script:
      - cmd: CALL "build\VS2017\build.bat" Build x64 Debug 1

  - # Clang x64 Debug
    matrix:
      only:
        - configuration: Debug
          platform: x64
          compiler: Clang

    build_script:
      - cmd: CALL "build\install_llvm.bat" 1
      - cmd: CALL "build\VS2017\build.bat" Build x64 LLVMDebug 1

  - # MSVC Win32 Debug
    matrix:
      only:
        - configuration: Debug
          platform: Win32
          compiler: MSVC

    build_script:
      - cmd: CALL "build\VS2017\build.bat" Build Win32 Debug 1

  - # Clang Win32 Debug
    matrix:
      only:
        - configuration: Debug
          platform: Win32
          compiler: Clang

    build_script:
      - cmd: CALL "build\install_llvm.bat" 1
      - cmd: CALL "build\VS2017\build.bat" Build Win32 LLVMDebug 1

  - # MSVC ARM64 Debug
    matrix:
      only:
        - configuration: Debug
          platform: ARM64
          compiler: MSVC

    build_script:
      - cmd: CALL "build\VS2017\build.bat" Build ARM64 Debug 1

  - # Clang ARM64 Debug
    matrix:
      only:
        - configuration: Debug
          platform: ARM64
          compiler: Clang

    build_script:
      - cmd: CALL "build\install_llvm.bat" 1
      - cmd: CALL "build\VS2017\build.bat" Build ARM64 LLVMDebug 1

  - # MSVC AVX2 Debug
    matrix:
      only:
        - configuration: Debug
          platform: AVX2
          compiler: MSVC

    build_script:
      - cmd: CALL "build\VS2017\build.bat" Build AVX2 Debug 1

  - # Clang AVX2 Debug
    matrix:
      only:
        - configuration: Debug
          platform: AVX2
          compiler: Clang

    build_script:
      - cmd: CALL "build\install_llvm.bat" 1
      - cmd: CALL "build\VS2017\build.bat" Build AVX2 LLVMDebug 1

  - # MSVC ARM Debug
    matrix:
      only:
        - configuration: Debug
          platform: ARM
          compiler: MSVC

    build_script:
      - cmd: CALL "build\VS2017\build.bat" Build ARM Debug 1

  - # Clang ARM Debug
    matrix:
      only:
        - configuration: Debug
          platform: ARM
          compiler: Clang

    build_script:
      - cmd: CALL "build\install_llvm.bat" 1
      - cmd: CALL "build\VS2017\build.bat" Build ARM LLVMDebug 1

  - # MSVC x64 Release
    matrix:
      only:
        - configuration: Release
          platform: x64
          compiler: MSVC

    build_script:
      - cmd: CALL "build\VS2017\build.bat" Build x64 Release 1
      - cmd: CALL "locale\build.bat" Build x64 Release 1
      - cmd: CALL "build\make_zip.bat" MSVC x64 Release Locale 1

    artifacts:
      - path: 'build\Notepad2*.zip'
        name: Notepad2_MSVC_i18n_x64

  - # Clang x64 Release
    matrix:
      only:
        - configuration: Release
          platform: x64
          compiler: Clang

    build_script:
      - cmd: CALL "build\install_llvm.bat" 1
      - cmd: CALL "build\VS2017\build.bat" Build x64 LLVMRelease 1
      - cmd: CALL "build\make_zip.bat" LLVM x64 Release 1

    artifacts:
      - path: 'build\Notepad2*.zip'
        name: Notepad2_Clang_MSVC_en_x64

  - # MSVC Win32 Release
    matrix:
      only:
        - configuration: Release
          platform: Win32
          compiler: MSVC

    build_script:
      - cmd: CALL "build\VS2017\build.bat" Build Win32 Release 1
      - cmd: CALL "locale\build.bat" Build Win32 Release 1
      - cmd: CALL "build\make_zip.bat" MSVC Win32 Release Locale 1

    artifacts:
      - path: 'build\Notepad2*.zip'
        name: Notepad2_MSVC_i18n_Win32

  - # Clang Win32 Release
    matrix:
      only:
        - configuration: Release
          platform: Win32
          compiler: Clang

    build_script:
      - cmd: CALL "build\install_llvm.bat" 1
      - cmd: CALL "build\VS2017\build.bat" Build Win32 LLVMRelease 1
      - cmd: CALL "build\make_zip.bat" LLVM Win32 Release 1

    artifacts:
      - path: 'build\Notepad2*.zip'
        name: Notepad2_Clang_MSVC_en_Win32

  - # MSVC AVX2 Release
    matrix:
      only:
        - configuration: Release
          platform: AVX2
          compiler: MSVC

    build_script:
      - cmd: CALL "build\VS2017\build.bat" Build AVX2 Release 1
      - cmd: CALL "locale\build.bat" Build AVX2 Release 1
      - cmd: CALL "build\make_zip.bat" MSVC AVX2 Release Locale 1

    artifacts:
      - path: 'build\Notepad2*.zip'
        name: Notepad2_MSVC_i18n_AVX2

  - # Clang AVX2 Release
    matrix:
      only:
        - configuration: Release
          platform: AVX2
          compiler: Clang

    build_script:
      - cmd: CALL "build\install_llvm.bat" 1
      - cmd: CALL "build\VS2017\build.bat" Build AVX2 LLVMRelease 1
      - cmd: CALL "build\make_zip.bat" LLVM AVX2 Release 1

    artifacts:
      - path: 'build\Notepad2*.zip'
        name: Notepad2_Clang_MSVC_en_AVX2

  - # MSVC ARM64 Release
    matrix:
      only:
        - configuration: Release
          platform: ARM64
          compiler: MSVC

    build_script:
      - cmd: CALL "build\VS2017\build.bat" Build ARM64 Release 1
      - cmd: CALL "locale\build.bat" Build ARM64 Release 1
      - cmd: CALL "build\make_zip.bat" MSVC ARM64 Release Locale 1

    artifacts:
      - path: 'build\Notepad2*.zip'
        name: Notepad2_MSVC_i18n_ARM64

  - # Clang ARM64 Release
    matrix:
      only:
        - configuration: Release
          platform: ARM64
          compiler: Clang

    build_script:
      - cmd: CALL "build\install_llvm.bat" 1
      - cmd: CALL "build\VS2017\build.bat" Build ARM64 LLVMRelease 1
      - cmd: CALL "build\make_zip.bat" LLVM ARM64 Release 1

    artifacts:
      - path: 'build\Notepad2*.zip'
        name: Notepad2_Clang_MSVC_en_ARM64

  - # MSVC ARM Release
    matrix:
      only:
        - configuration: Release
          platform: ARM
          compiler: MSVC

    build_script:
      - cmd: CALL "build\VS2017\build.bat" Build ARM Release 1
      - cmd: CALL "build\make_zip.bat" MSVC ARM Release 1

    artifacts:
      - path: 'build\Notepad2*.zip'
        name: Notepad2_MSVC_ARM_en

  - # Clang ARM Release
    matrix:
      only:
        - configuration: Release
          platform: ARM
          compiler: Clang

    build_script:
      - cmd: CALL "build\install_llvm.bat" 1
      - cmd: CALL "build\VS2017\build.bat" Build ARM LLVMRelease 1
      - cmd: CALL "build\make_zip.bat" LLVM ARM Release 1

    artifacts:
      - path: 'build\Notepad2*.zip'
        name: Notepad2_Clang_MSVC_en_ARM
