name: CI

on: [push, pull_request]

defaults:
  run:
    shell: cmd

jobs:
  msvc_build:
    name: Build with Visual C++
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: MSVC x64 Release
      run: |
        CALL "build\VS2017\build.bat" Build x64 Release 1
        CALL "locale\build.bat" Build x64 Release 1
        CALL "build\make_zip.bat" MSVC x64 Release Locale 1

    - name: MSVC Win32 Release
      run: |
        CALL "build\VS2017\build.bat" Build Win32 Release 1
        CALL "locale\build.bat" Build Win32 Release 1
        CALL "build\make_zip.bat" MSVC Win32 Release Locale 1

    - name: MSVC AVX2 Release
      run: |
        CALL "build\VS2017\build.bat" Build AVX2 Release 1
        CALL "locale\build.bat" Build AVX2 Release 1
        CALL "build\make_zip.bat" MSVC AVX2 Release Locale 1

    - name: MSVC ARM64 Release
      run: |
        CALL "build\VS2017\build.bat" Build ARM64 Release 1
        CALL "locale\build.bat" Build ARM64 Release 1
        CALL "build\make_zip.bat" MSVC ARM64 Release Locale 1

    - name: MSVC ARM Release
      run: |
        CALL "build\VS2017\build.bat" Build ARM Release 1
        CALL "build\make_zip.bat" MSVC ARM Release 1

    - uses: actions/upload-artifact@v2
      with:
          name: Notepad2_i18n_x64
          path: 'build\Notepad2_i18n_x64_*.zip'

    - uses: actions/upload-artifact@v2
      with:
          name: Notepad2_i18n_Win32
          path: 'build\Notepad2_i18n_Win32_*.zip'

    - uses: actions/upload-artifact@v2
      with:
          name: Notepad2_i18n_AVX2
          path: 'build\Notepad2_i18n_AVX2_*.zip'

    - uses: actions/upload-artifact@v2
      with:
          name: Notepad2_i18n_ARM64
          path: 'build\Notepad2_i18n_ARM64_*.zip'

    - uses: actions/upload-artifact@v2
      with:
          name: Notepad2_ARM
          path: 'build\Notepad2_ARM_*.zip'

  clang_build:
    name: Build with Clang
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install LLVM
      run: |
        CALL "build\install_llvm.bat" latest 1

    - name: Clang x64 Release
      run: |
        CALL "build\VS2017\build.bat" Build x64 LLVMRelease 1
        CALL "build\make_zip.bat" Clang x64 Release 1

    - name: Clang Win32 Release
      run: |
        CALL "build\VS2017\build.bat" Build Win32 LLVMRelease 1
        CALL "build\make_zip.bat" Clang Win32 Release 1

    - name: Clang AVX2 Release
      run: |
        CALL "build\VS2017\build.bat" Build AVX2 LLVMRelease 1
        CALL "build\make_zip.bat" Clang AVX2 Release 1

    - name: Clang ARM64 Release
      run: |
        CALL "build\VS2017\build.bat" Build ARM64 LLVMRelease 1
        CALL "build\make_zip.bat" Clang ARM64 Release 1

    #- name: Clang ARM Release
    #  run: |
    #    CALL "build\VS2017\build.bat" Build ARM LLVMRelease 1
    #    CALL "build\make_zip.bat" Clang ARM Release 1

    - uses: actions/upload-artifact@v2
      with:
          name: Notepad2_Clang_x64
          path: 'build\Notepad2_Clang_x64_*.zip'

    - uses: actions/upload-artifact@v2
      with:
          name: Notepad2_Clang_Win32
          path: 'build\Notepad2_Clang_Win32_*.zip'

    - uses: actions/upload-artifact@v2
      with:
          name: Notepad2_Clang_AVX2
          path: 'build\Notepad2_Clang_AVX2_*.zip'

    - uses: actions/upload-artifact@v2
      with:
          name: Notepad2_Clang_ARM64
          path: 'build\Notepad2_Clang_ARM64_*.zip'

    #- uses: actions/upload-artifact@v2
    #  with:
    #      name: Notepad2_Clang_ARM
    #      path: 'build\Notepad2_Clang_ARM_*.zip'
